// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(SalutICamesDbContext))]
    partial class SalutICamesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.CatalogueContext.Entities.Catalogue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Catalogues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("972008bb-bbca-4bea-bfb2-2d4b2f9ef31b"),
                            Name = "Repte dels 100 Cims de la FEEC"
                        });
                });

            modelBuilder.Entity("Domain.CatalogueContext.Entities.Summit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Altitude")
                        .HasColumnType("int")
                        .HasColumnName("Altitude");

                    b.Property<Guid?>("CatalogueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Region");

                    b.ToTable("Summits", (string)null);
                });

            modelBuilder.Entity("Domain.ChallengeContext.Entities.Climb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AscensionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HikerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SummitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("HikerId", "SummitId");

                    b.HasIndex("DiaryId");

                    b.ToTable("Climbs", (string)null);
                });

            modelBuilder.Entity("Domain.ChallengeContext.Entities.Diary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HikerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HikerId")
                        .IsUnique();

                    b.ToTable("Diaries", (string)null);
                });

            modelBuilder.Entity("Domain.ChallengeContext.Entities.Hiker", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Hikers", (string)null);
                });

            modelBuilder.Entity("Persistence.Data.EnumLookup<Domain.CatalogueContext.Enums.Region>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnumLookup<Region>");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pla de l'Estany",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Garrotxa",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ripollès",
                            Value = 3
                        },
                        new
                        {
                            Id = -1,
                            Name = "NONE",
                            Value = -1
                        });
                });

            modelBuilder.Entity("Domain.CatalogueContext.Entities.Summit", b =>
                {
                    b.HasOne("Domain.CatalogueContext.Entities.Catalogue", null)
                        .WithMany("Summits")
                        .HasForeignKey("CatalogueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Persistence.Data.EnumLookup<Domain.CatalogueContext.Enums.Region>", null)
                        .WithMany()
                        .HasForeignKey("Region")
                        .HasPrincipalKey("Value")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.ChallengeContext.Entities.Climb", b =>
                {
                    b.HasOne("Domain.ChallengeContext.Entities.Diary", null)
                        .WithMany("Climbs")
                        .HasForeignKey("DiaryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.ChallengeContext.Entities.Diary", b =>
                {
                    b.HasOne("Domain.ChallengeContext.Entities.Hiker", "Hiker")
                        .WithOne()
                        .HasForeignKey("Domain.ChallengeContext.Entities.Diary", "HikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hiker");
                });

            modelBuilder.Entity("Domain.CatalogueContext.Entities.Catalogue", b =>
                {
                    b.Navigation("Summits");
                });

            modelBuilder.Entity("Domain.ChallengeContext.Entities.Diary", b =>
                {
                    b.Navigation("Climbs");
                });
#pragma warning restore 612, 618
        }
    }
}
